name       : libxrender
version    : 0.9.10
release    : 11
source     :
    - https://www.x.org/releases/individual/lib/libXrender-0.9.10.tar.gz : 770527cce42500790433df84ec3521e8bf095dfe5079454a92236494ab296adf
license    :
    - MIT
summary    : X Rendering Extension client library
component  : xorg.library
description: |
    The X Rendering Extension (Render) introduces digital image composition as
    the foundation of a new rendering model within the X Window System.
    Rendering geometric figures is accomplished by client-side tessellation into
    either triangles or trapezoids.
    Text is drawn by loading glyphs into the server and rendering sets of them.
    The Xrender library exposes this extension to X clients.
builddeps  :
    - pkgconfig(renderproto)
    - pkgconfig(xproto)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
