name       : libxrender
version    : 0.9.10
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libXrender-0.9.10.tar.gz : 770527cce42500790433df84ec3521e8bf095dfe5079454a92236494ab296adf
license    : MIT
component  : xorg.library
summary    : X Rendering Extension client library
description: |
    The X Rendering Extension (Render) introduces digital image composition as the foundation of a new rendering model within the X Window System. Rendering geometric figures is accomplished by client-side tessellation into either triangles or trapezoids. Text is drawn by loading glyphs into the server and rendering sets of them. The Xrender library exposes this extension to X clients.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig(xproto)
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
