name        : libxrender
version     : 0.9.8
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.8.tar.gz : c3acffff4cd5c91585e8c4fdf1ec29fc234482f661ed548112b4d52db19963d1
license     :
    - MIT
summary     : X Rendering Extension client library
builddeps   :
    - pkgconfig(renderproto)
    - pkgconfig(xproto)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    The X Rendering Extension (Render) introduces digital image composition as the foundation of a new rendering model within the X Window System. Rendering geometric figures is accomplished by client-side tessellation into either triangles or trapezoids.  Text is drawn by loading glyphs into the server and rendering sets of them.  The Xrender library exposes this extension to X clients.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
