name        : libxrender
version     : 0.9.9
release     : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.9.tar.bz2 : fc2fe57980a14092426dffcd1f2d9de0987b9d40adea663bd70d6342c0e9be1a
license     :
    - MIT
summary     : X Rendering Extension client library
component   : xorg.library
builddeps   :
    - pkgconfig(renderproto)
    - pkgconfig(xproto)
    - pkgconfig32(x11)
    - pkgconfig(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
description : |
    The X Rendering Extension (Render) introduces digital image composition as the foundation of a new rendering model within the X Window System. Rendering geometric figures is accomplished by client-side tessellation into either triangles or trapezoids.  Text is drawn by loading glyphs into the server and rendering sets of them.  The Xrender library exposes this extension to X clients.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
